title: Page
pages: true
files: true
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
    
  metatag:
    label: Metatags
    type: headline
  metaTitle:
    label: Title
    type: text
  metaDescription:
    label: Description
    type: textarea