title: Site

# pages: 
#   template:
#     - default
#     - landing

fields:
  title:
    label: Title
    type:  text
  description:
    label: Description
    type:  textarea

  aboutUs:
    label: About Us
    type: textarea

  contact:
    label: Email
    type: headline
  contactTo:
    label: To
    type: email
    width: 1/2
  contactBcc:
    label: Bcc
    type: email
    width: 1/2

  mailChimp:
    label: Mailchimp
    type:  text
    help: Please enter the Mailchimp "form action"

  tagManager:
    label: Tag Manager
    type:  textarea