title: Site

pages: 
  template:
    - default
    - landing

fields:
  title:
    label: Title
    type:  text

  description:
    label: Description
    type:  textarea

  aboutUs:
    label: About Us
    type: textarea